# Generated by Django 6.0 on 2026-04-18 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0006_alter_loaixe_options_loaixe_kieu_xe_and_more'),
        ('customers', '0002_alter_khachhang_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='HopDong',
            fields=[
                ('ma_hd', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Mã hợp đồng')),
                ('ngay_lap', models.DateTimeField(auto_now_add=True, verbose_name='Ngày lập hợp đồng')),
                ('ngay_bat_dau', models.DateTimeField(verbose_name='Ngày bắt đầu')),
                ('ngay_ket_thuc_du_kien', models.DateTimeField(verbose_name='Ngày kết thúc dự kiến')),
                ('ngay_ket_thuc_thuc_te', models.DateTimeField(blank=True, null=True, verbose_name='Ngày kết thúc thực tế')),
                ('tong_tien_thue', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Tổng tiền thuê')),
                ('tien_coc', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Tiền cọc')),
                ('tien_tra_truoc', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Tiền trả trước')),
                ('trang_thai', models.CharField(default='Chờ nhận xe', max_length=50, verbose_name='Trạng thái')),
                ('khach_hang', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='customers.khachhang', verbose_name='Khách hàng')),
            ],
            options={
                'verbose_name': 'Hợp đồng thuê',
                'db_table': 'HOPDONGTHUE',
            },
        ),
        migrations.CreateModel(
            name='PhieuGiaHan',
            fields=[
                ('ma_gh', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Mã gia hạn')),
                ('ngay_ket_thuc_moi', models.DateTimeField(verbose_name='Ngày kết thúc mới')),
                ('tien_thue_phat_sinh', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Tiền thuê phát sinh')),
                ('hop_dong', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='rentals.hopdong', verbose_name='Hợp đồng')),
            ],
            options={
                'verbose_name': 'Phiếu gia hạn hợp đồng',
                'db_table': 'PHIEUGIAHANHOPDONG',
            },
        ),
        migrations.CreateModel(
            name='PhieuTraXe',
            fields=[
                ('ma_tra_xe', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Mã trả xe')),
                ('ngay_tra_thuc_te', models.DateTimeField(auto_now_add=True, verbose_name='Ngày trả thực tế')),
                ('phat_qua_han', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Phạt quá hạn')),
                ('phu_phi_khac', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Phụ phí khác')),
                ('tien_tra_lai_khach', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Tiền trả lại khách')),
                ('khach_tra_them', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Khách trả thêm')),
                ('ghi_chu', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('hop_dong', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='rentals.hopdong', verbose_name='Hợp đồng')),
            ],
            options={
                'verbose_name': 'Phiếu trả xe',
                'db_table': 'PHIEUTRAXE',
            },
        ),
        migrations.CreateModel(
            name='ChiTietHopDong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xe', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cars.xe', verbose_name='Xe')),
                ('hop_dong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.hopdong', verbose_name='Hợp đồng')),
            ],
            options={
                'verbose_name': 'Chi tiết hợp đồng',
                'db_table': 'HOPDONGTHUE_CHITIET',
                'unique_together': {('hop_dong', 'xe')},
            },
        ),
    ]
