# Generated by Django 6.0 on 2026-04-18 12:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hopdong',
            name='ngay_lap',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày lập hợp đồng'),
        ),
    ]
