# Generated by Django 6.0 on 2026-04-18 16:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_alter_hopdong_ngay_lap'),
    ]

    operations = [
        migrations.CreateModel(
            name='LichSuThayDoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_thay_doi', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày thay đổi')),
                ('noi_dung', models.TextField(verbose_name='Nội dung thay đổi')),
                ('tien_chenh_lech', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Tiền chênh lệch')),
                ('hop_dong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.hopdong', verbose_name='Hợp đồng')),
            ],
            options={
                'verbose_name': 'Lịch sử thay đổi hợp đồng',
                'db_table': 'HOPDONGTHUE_LICHSU',
            },
        ),
        migrations.DeleteModel(
            name='PhieuGiaHan',
        ),
    ]
