# Generated by Django 6.0.4 on 2026-04-19 16:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_lichsuthaydoi_delete_phieugiahan'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiaoDich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_gd', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày giao dịch')),
                ('so_tien', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='Số tiền')),
                ('loai_gd', models.CharField(choices=[('Tạm ứng', 'Tạm ứng'), ('Thu thêm', 'Thu thêm'), ('Hoàn trả', 'Hoàn trả'), ('Quyết toán', 'Quyết toán')], max_length=50, verbose_name='Loại giao dịch')),
                ('ghi_chu', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('hop_dong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giao_dich_set', to='rentals.hopdong', verbose_name='Hợp đồng')),
            ],
            options={
                'verbose_name': 'Giao dịch tài chính',
                'db_table': 'HOPDONGTHUE_GIAODICH',
                'ordering': ['-ngay_gd'],
            },
        ),
    ]
