# Generated by Django 6.0.4 on 2026-04-20 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_giaodich'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giaodich',
            name='ghi_chu',
        ),
    ]
