# Generated by Django 6.0.3 on 2026-04-25 02:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_remove_giaodich_ghi_chu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giaodich',
            name='ngay_gd',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Ngày giao dịch'),
        ),
        migrations.AlterField(
            model_name='hopdong',
            name='ngay_bat_dau',
            field=models.DateField(verbose_name='Ngày bắt đầu'),
        ),
        migrations.AlterField(
            model_name='hopdong',
            name='ngay_ket_thuc_du_kien',
            field=models.DateField(verbose_name='Ngày kết thúc dự kiến'),
        ),
        migrations.AlterField(
            model_name='hopdong',
            name='ngay_ket_thuc_thuc_te',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc thực tế'),
        ),
        migrations.AlterField(
            model_name='phieutraxe',
            name='ngay_tra_thuc_te',
            field=models.DateField(auto_now_add=True, verbose_name='Ngày trả thực tế'),
        ),
    ]
