# Generated by Django 6.0.4 on 2026-04-22 14:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_alter_hopdong_ngay_bat_dau_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giaodich',
            name='ngay_gd',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Ngày giao dịch'),
        ),
    ]
