# Generated by Django 6.0.3 on 2026-05-02 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_alter_giaodich_ngay_gd_alter_hopdong_ngay_bat_dau_and_more'),
        ('rentals', '0007_alter_giaodich_ngay_gd'),
    ]

    operations = [
    ]
