# Generated by Django 6.0.4 on 2026-04-17 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HangXe',
            fields=[
                ('ma_hang', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Mã hãng xe')),
                ('ten_hang', models.CharField(max_length=100, unique=True, verbose_name='Tên hãng xe')),
            ],
            options={
                'db_table': 'HANGXE',
            },
        ),
        migrations.CreateModel(
            name='KieuXe',
            fields=[
                ('ma_kieu', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Mã kiểu xe')),
                ('ten_kieu', models.CharField(max_length=100, unique=True, verbose_name='Tên kiểu xe')),
            ],
            options={
                'db_table': 'KIEUXE',
            },
        ),
        migrations.CreateModel(
            name='MauSac',
            fields=[
                ('ma_mau', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Mã màu')),
                ('ten_mau', models.CharField(max_length=50, unique=True, verbose_name='Tên màu')),
            ],
            options={
                'db_table': 'MAUSAC',
            },
        ),
        migrations.CreateModel(
            name='QuocGia',
            fields=[
                ('ma_quoc_gia', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Mã quốc gia')),
                ('ten_quoc_gia', models.CharField(max_length=100, unique=True, verbose_name='Tên quốc gia')),
            ],
            options={
                'verbose_name': 'Quốc gia',
                'db_table': 'QUOCGIA',
            },
        ),
        migrations.CreateModel(
            name='LoaiXe',
            fields=[
                ('ma_loai', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Mã loại xe')),
                ('ten_loai', models.CharField(max_length=100, unique=True, verbose_name='Tên loại xe (dòng xe)')),
                ('so_cho_ngoi', models.IntegerField(verbose_name='Số chỗ ngồi')),
                ('hang_xe', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cars.hangxe', verbose_name='Hãng xe')),
                ('kieu_xe', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cars.kieuxe', verbose_name='Kiểu xe')),
            ],
            options={
                'db_table': 'LOAIXE',
            },
        ),
        migrations.AddField(
            model_name='hangxe',
            name='quoc_gia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cars.quocgia', verbose_name='Quốc gia'),
        ),
        migrations.CreateModel(
            name='Xe',
            fields=[
                ('bien_so', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Biển số xe')),
                ('gia_thue_ngay', models.IntegerField(verbose_name='Giá thuê ngày')),
                ('gia_thue_gio', models.IntegerField(verbose_name='Giá thuê giờ')),
                ('trang_thai', models.CharField(default='Sẵn sàng', max_length=50, verbose_name='Trạng thái')),
                ('loai_xe', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cars.loaixe', verbose_name='Loại xe')),
                ('mau_sac', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cars.mausac', verbose_name='Màu sắc')),
            ],
            options={
                'db_table': 'XE',
            },
        ),
        migrations.CreateModel(
            name='LichSuBaoTri',
            fields=[
                ('ma_bao_tri', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã bảo trì')),
                ('loai_bao_tri', models.CharField(max_length=100, verbose_name='Loại bảo trì')),
                ('ngay_bao_tri', models.DateField(verbose_name='Ngày bảo trì')),
                ('chi_phi', models.IntegerField(verbose_name='Chi phí')),
                ('xe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.xe', verbose_name='Xe')),
            ],
            options={
                'db_table': 'LICHSUBAOTRI',
            },
        ),
    ]
