# Generated by Django 6.0.4 on 2026-04-17 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xe',
            name='gia_thue_gio',
        ),
        migrations.AlterField(
            model_name='xe',
            name='mau_sac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cars.mausac', verbose_name='Màu sơn'),
        ),
        migrations.AlterField(
            model_name='xe',
            name='trang_thai',
            field=models.CharField(default='Có sẵn', max_length=50, verbose_name='Trạng thái hoạt động'),
        ),
    ]
