# Generated by Django 6.0.4 on 2026-04-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_remove_xe_gia_thue_gio_alter_xe_mau_sac_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lichsubaotri',
            name='noi_dung_chi_tiet',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nội dung chi tiết'),
        ),
    ]
