# Generated by Django 6.0.4 on 2026-04-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_lichsubaotri_noi_dung_chi_tiet'),
    ]

    operations = [
        migrations.AddField(
            model_name='xe',
            name='nam_san_xuat',
            field=models.IntegerField(default=2022, verbose_name='Năm sản xuất'),
        ),
    ]
