# Generated by Django 6.0.4 on 2026-04-18 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_xe_nam_san_xuat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loaixe',
            name='kieu_xe',
        ),
        migrations.AddField(
            model_name='xe',
            name='kieu_xe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='cars.kieuxe', verbose_name='Kiểu xe'),
        ),
        migrations.AlterField(
            model_name='xe',
            name='trang_thai',
            field=models.CharField(default='Sẵn sàng', max_length=50, verbose_name='Trạng thái hoạt động'),
        ),
    ]
