# Generated by Django 6.0 on 2026-04-18 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_remove_loaixe_kieu_xe_xe_kieu_xe_alter_xe_trang_thai'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loaixe',
            options={'verbose_name': 'Loại xe'},
        ),
        migrations.AddField(
            model_name='loaixe',
            name='kieu_xe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='cars.kieuxe', verbose_name='Kiểu xe'),
        ),
        migrations.AlterField(
            model_name='loaixe',
            name='ten_loai',
            field=models.CharField(max_length=100, unique=True, verbose_name='Tên loại xe'),
        ),
    ]
