# Generated by Django 6.0 on 2026-04-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_loaixe_options_loaixe_kieu_xe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lichsubaotri',
            name='ngay_ket_thuc',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc dự kiến'),
        ),
        migrations.AlterField(
            model_name='lichsubaotri',
            name='ngay_bao_tri',
            field=models.DateField(verbose_name='Ngày bắt đầu bảo trì'),
        ),
    ]
