# Generated by Django 6.0.4 on 2026-04-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('ma_kh', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Mã khách hàng')),
                ('ho_ten', models.CharField(max_length=100, verbose_name='Họ và tên')),
                ('so_dien_thoai', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('cccd', models.CharField(max_length=20, unique=True, verbose_name='CCCD/CMND')),
                ('trang_thai', models.CharField(default='Bình thường', max_length=50, verbose_name='Trạng thái')),
            ],
            options={
                'verbose_name': 'Khách hàng',
                'verbose_name_plural': 'Danh sách khách hàng',
            },
        ),
    ]
