# Generated by Django 6.0.4 on 2026-04-17 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='khachhang',
            table='KHACHHANG',
        ),
    ]
