# Generated by Django 6.0.4 on 2026-04-28 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_khachhang_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='khachhang',
            name='trang_thai',
        ),
    ]
